### ISSUE TITLE
User Management

### ISSUE THREAD

**Issue by Carlos12001** [Bases-Crew/TECAir#1]
## Task
- [x] User creation
- [x] Data validation (full name, phone, email)
- [x] Option to mark as a student
- [x] If a student, capture additional information (university, ID card)
- [x] Loyalty program and miles
