### ISSUE TITLE
Passenger Check-in

### ISSUE THREAD

**Issue by diabloget** [Bases-Crew/TECAir#15]
## Task
- [x] Save user and flight data
- [x] Generate flight ticket (PDF)
- [x] Send ticket through an email, or print pdf
