### ISSUE TITLE
Flight Search

### ISSUE THREAD

**Issue by Carlos12001** [Bases-Crew/TECAir#3]
## Task

- [x] Input for departure airport
- [x] Input for arrival airport
- [x] Display search results
