### ISSUE TITLE
Promotions Display

### ISSUE THREAD

**Issue by Carlos12001** [Bases-Crew/TECAir#6]
## Task

- [x] Exclusive area for announcements
- [x] List of promotions
- [x] Details for each promotion
