### ISSUE TITLE
mobile flight search

### ISSUE THREAD

**Issue by Apollo13-0** [Bases-Crew/TECAir#8]
## Task
- [x] flight search
- [x] add departure and arrival city
- [x] display available flights
- [x] display basic flight information
